### ISSUE TITLE
如果能加上搜索引擎就更棒了

### ISSUE THREAD

**Issue by UPToZ-Core** [zhheo/halo-theme-heolink#1]
希望能够加一个搜索引擎

**Comment by chenkuicn** [comment]
要是能做成自定义页面模板就更好了，不用再开一个站点

**Comment by zhheo** [comment]
> 希望能够加一个搜索引擎

好建议，下个版本添加

**Comment by zhheo** [comment]
> 要是能做成自定义页面模板就更好了，不用再开一个站点

后续会增加一些文章显示相关的模块

**Comment by chenkuicn** [comment]
> > 要是能做成自定义页面模板就更好了，不用再开一个站点
> 
> 后续会增加一些文章显示相关的模块

可以考虑把[张洪 Heo](https://blog.zhheo.com/)主题直接做Halo适配么？可以付费。我知道已经有移植了。
另外我说的自定义页面模板的话对于不想再开站点的用户比较好（包括落地页模板），当然只想做导航站的话安装这个主题完全没问题。

**Comment by wxyShine** [comment]
> 要是能做成自定义页面模板就更好了，不用再开一个站点

应该是做成插件类似[douban](https://github.com/chengzhongxue/plugin-douban)吧 会给halo加一个路由地址

**Comment by chenkuicn** [comment]
> > 要是能做成自定义页面模板就更好了，不用再开一个站点
> 
> 应该是做成插件类似[douban](https://github.com/chengzhongxue/plugin-douban)吧 会给halo加一个路由地址
插件也是一种方式，我买了halo的pix里面有落地页的自定义页面模板，这个是在主题里面的。

**Comment by zhheo** [comment]
0.4已支持搜索引擎的设置，感谢你的反馈。
<img width="733" alt="image" src="https://github.com/zhheo/halo-theme-heolink/assets/33177975/32a15e8e-7846-41ae-9996-5c0f4076acea">
