### ISSUE TITLE
【建议】自定义网站顺序

### ISSUE THREAD

**Issue by CLOT-LIU** [zhheo/halo-theme-heolink#10]
希望能够自定义网站的顺序，因为有的网站用的多，希望能放在第一位

**Comment by zhheo** [comment]
<img width="650" alt="image" src="https://github.com/user-attachments/assets/8f4b3804-4a7b-469e-9535-80054bcbd131">
拖动调整顺序

**Comment by CLOT-LIU** [comment]
> <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/33177975/354103338-8f4b3804-4a7b-469e-9535-80054bcbd131.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTMzNDUsIm5iZiI6MTcyMjQ5MzA0NSwicGF0aCI6Ii8zMzE3Nzk3NS8zNTQxMDMzMzgtOGY0YjM4MDQtNGE3Yi00NjllLTk1MzUtODAwNTRiY2JkMTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2MTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmM2U0NjIyNDkzMDQ4MzUxYmUzN2Q2YWIyYjA0ZDg5ZmEzOWI5NTc3YmE2NTkyY2IxNjM1YTBjODU5NTFlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.72PcXmTFCax22MVrmOqqPaZUEgtmIaWgbxWVxsIGa5A"> 拖动调整顺序

好的，谢谢
