### ISSUE TITLE
能否考虑增加快捷切换内网与公网访问模式？

### ISSUE THREAD

**Issue by 29929459** [zhheo/halo-theme-heolink#11]
内网与公网访问地址不同，在网页某个角落增加固定显示切换内网与公网访问的按钮，并且可以设置不需要或者需要登录登录才可以切换的效果，所以能否考虑增加快捷切换内网与公网访问模式呢？类似于图片下面这个网站效果~
![微信图片_20240824164051](https://github.com/user-attachments/assets/cf19f6b2-f2fa-486a-a226-f495aa4e95d4)

**Comment by zhheo** [comment]
推荐使用洪绘畅联：https://blog.zhheo.com/p/f0d4.html
