### ISSUE TITLE
元数据导致所有链接失效

### ISSUE THREAD

**Issue by yangjiacheng1996** [zhheo/halo-theme-heolink#13]
链接管理插件版本：1.5.0
Heolink主题版本：0.8
问题描述：在后台左侧点击链接管理，新建链接时，填写完网站地址、网站名称、Logo后，下方元数据一栏默认会关联halo网站的一篇文章，且无法取消，导致我新建的所有链接都会跳转到文章，而不是对应的网站。所有链接失效，这个网址导航主题也会变得毫无意义。请项目owner看看这个问题是halo官方插件“链接管理”的bug，还是Heolink主题的兼容性问题，谢谢
![heolink-issue](https://github.com/user-attachments/assets/a0ce90e0-cae3-43a6-b992-3ed47dc441f6)

**Comment by zhheo** [comment]
请使用最新版本
