### ISSUE TITLE
批量导入需要做什么额外配置吗?

### ISSUE THREAD

**Issue by laogou717** [zhheo/halo-theme-heolink#14]
在**halo**的管理页面,我上传的时候总是**失败**,想问下是不是需要做一些**额外的配置**,或者是需要什么**固定的格式**?  有**模板**吗?
<img width="767" alt="image" src="https://github.com/user-attachments/assets/e2025b95-c6d7-4c11-856a-5a5f8fe1bd9d">

**Comment by zhheo** [comment]
我无法针对Halo的官方功能提供任何建议，因为我并不使用Halo，建议到询问官方客服。
