### ISSUE TITLE
优化意见

### ISSUE THREAD

**Issue by yotoome** [zhheo/halo-theme-heolink#15]
尊敬的作者您好, 感谢您开发并免费公布了这么好的项目。

下面是小弟的一些意见，希望您能在百忙之中抽空查看

1 . 无法直观的调整栏目的顺序。甚至调整不了。
![无法调整顺序](https://github.com/user-attachments/assets/6062e66f-b1c4-477b-8cf8-41f64c160b48)

2. 分类不够直观, 无法清晰的直观的感受到每个栏目，我给您找了一个参考
![分类不够直观](https://github.com/user-attachments/assets/6f3901e4-3efe-4128-8a05-dda3ccecfec5)

参考图:
![参考](https://github.com/user-attachments/assets/843a0a4d-1ab6-4bd1-ab77-e2c3761b1aa0)

3. 是我觉得没有层次感,如果栏目组和中间一样的颜色 层次感会非常的低
参考图
![层次感](https://github.com/user-attachments/assets/f3dc5d76-890c-41d4-b708-651944cebee9)

其次呢 我希望能够添加一个中间背景替换的 功能
-----------------------------------------------------------------------

以上是小老弟用了几天的感受，并没有提要求的意思，只是希望能够帮助这么好的项目增加一点点帮助。自己的看法。

**Comment by zhheo** [comment]
1.可以通过拖拽左侧的调整顺序来调
2.分类标题图标可以自定义，详见演示站：halo.zhheo.com
3.暂不考虑
4.背景替换暂不考虑
