### ISSUE TITLE
无法直接跳转

### ISSUE THREAD

**Issue by yyhatb** [zhheo/halo-theme-heolink#16]
请问下我部署完成后，在链接管理里面添加完链接后，回到网站中点击其中的导航链接的时候，不是直接跳转到对应网站，这个应该怎么设置一下呢

**Comment by zhheo** [comment]
<img width="779" alt="image" src="https://github.com/user-attachments/assets/df2427e8-01e7-45d0-a4ad-d12b78bd917f">

**Comment by yyhatb** [comment]
我就是这样设置的，您访问下看看，http://dev.sixsix.site:8090/

**Comment by zhheo** [comment]
地址没带https协议头

**Comment by yyhatb** [comment]
好的，好的，可以了，感谢
