### ISSUE TITLE
很喜欢这个简约风格

### ISSUE THREAD

**Issue by luyabing** [zhheo/halo-theme-heolink#17]
有点小建议，手机页面，左侧分组导航，能不能不要做全屏，或者点击后自动切换到首页也行，现在点击看不到效果，而且是全屏，感觉跟没点一样。PC的页面搜索能不能加一个切换搜索引擎的功能，还有在主题里希望可以自由设置搜索引擎。

**Comment by zhheo** [comment]
1.现在全屏主要是写的比较方便（手机端目前只是做简单的可用性适配），后续有机会优化的话可以改
2.切换搜索引擎目前前端做起来比较麻烦，暂时没有这方面精力。自由设置搜索引擎的话可以发我，我后续版本加上去也行（提新issues）
