### ISSUE TITLE
[BUG]侧边栏展示信息错误

### ISSUE THREAD

**Issue by carolcoral** [zhheo/halo-theme-heolink#18]
## Version
* halo: 2.20.3
* heolink: 0.8

## Description
在链接管理里面设置了`友情链接`分组不展示，在页面上右侧内容中没有展示，但是，在左侧侧边栏菜单信息中仍然存在

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/c3057572-70fc-4e30-9c31-ca4940ec2d6d">

**Comment by zhheo** [comment]
已修复，下个版本可用
