### ISSUE TITLE
希望能支持设置一行数量

### ISSUE THREAD

**Issue by sunkolin** [zhheo/halo-theme-heolink#19]
希望能支持设置一行数量

**Comment by zhheo** [comment]
一行数量取决于屏幕宽度，自动计算，不支持修改

**Comment by sunkolin** [comment]
能否支持设置一行4列，一行5列，一行6列呢？我的电脑是分辨率是2880 × 1800，显示的是4列，每个内容有点宽。

**Comment by zhheo** [comment]
已针对高分辨率屏幕优化，下个版本上线
