### ISSUE TITLE
分类超过14个时，首页展示的第一个第二个分类会错乱，丢失

### ISSUE THREAD

**Issue by sunkolin** [zhheo/halo-theme-heolink#21]
<img width="242" alt="image" src="https://github.com/user-attachments/assets/0c347ba5-8820-4086-88ea-163ebc0ec8e6">

**Comment by zhheo** [comment]
可以提供一个链接吗

**Comment by zhheo** [comment]
0.11已修复

**Comment by sunkolin** [comment]
我的网站是 https://52xe.top/

**Comment by zhheo** [comment]
是8.11版本没修复吗

**Comment by sunkolin** [comment]
我使用的是macbookpro是这样的，家里的电脑windows的， 浏览器最大化后没出现这个问题；如果把浏览器缩小点，左侧分类会出现一个导航条，此时也滑不到最上面的分类

**Comment by sunkolin** [comment]
> 是0.11版本没修复吗

刚看到您的回复，我升级一下看看

**Comment by sunkolin** [comment]
已经修复了，感谢大神
