### ISSUE TITLE
希望支持设置默认图标

### ISSUE THREAD

**Issue by sunkolin** [zhheo/halo-theme-heolink#25]
希望支持设置默认图标
有些网站没有图标，希望可以有一个设置替代图标的地方。现在获取不到图标的网站是一个灰色的图标，不好看

**Comment by zhheo** [comment]
指的是灰色的地球图标吗？那个是api的图标无法更改，建议自行搭建网站图标获取api，或者可以自行上传图标。

**Comment by sunkolin** [comment]
自行上传很麻烦，如果想换图标，每个链接都需要换一遍，链接很多比较麻烦

**Comment by zhheo** [comment]
那个是api的图标无法更改，建议自行搭建网站图标获取api

**Comment by zhheo** [comment]
在主题设置可以更改api地址
