### ISSUE TITLE
发布版本建议同时修改 theme.yaml 的 version

### ISSUE THREAD

**Issue by ruibaby** [zhheo/halo-theme-heolink#4]
否则可能造成应用市场更新时，版本校验不准确。

可以看到 0.5 已发布：<https://github.com/zhheo/halo-theme-heolink/releases/tag/0.5>，但 theme.yaml 中的 version 仍然是 0.4.3。

**Comment by zhheo** [comment]
抱歉。已经更改到0.5.1版本
