### ISSUE TITLE
这个主题安装好了打开直接500报错，预览也是500报错

### ISSUE THREAD

**Issue by bulibuqiyaoyao133** [zhheo/halo-theme-heolink#5]
![image](https://github.com/zhheo/halo-theme-heolink/assets/79575346/e690462c-ae3d-4187-95b6-b4bb77beb925)
这个主题安装好了打开直接500报错，预览也是500报错

**Comment by zhheo** [comment]
请安装“链接管理”插件。
https://www.halo.run/store/apps/app-hfbQg
另外感谢你的反馈，下个版本将修复这个错误提示没有正确显示的问题。
