### ISSUE TITLE
【BUG】预览情况下的跳转

### ISSUE THREAD

**Issue by carolcoral** [zhheo/halo-theme-heolink#6]
因为主题主要是一个类导航站，因此主要用`预览`方式做兼容展示，但是当使用预览方式访问的时候点击左侧分组跳转会丢失关键参数，导致无法正确跳转到对应分组上

站点: [https://oyiso.xindu.site/?preview-theme=theme-heolink](https://oyiso.xindu.site/?preview-theme=theme-heolink)

<img width="1677" alt="image" src="https://github.com/zhheo/halo-theme-heolink/assets/8952687/2d887401-f2cf-499d-bfba-508be151e0b8">

**点击跳转后地址错误，丢失参数**

<img width="1678" alt="image" src="https://github.com/zhheo/halo-theme-heolink/assets/8952687/1ebde9b5-136f-43b0-86c8-e70cb917b019">

**Comment by zhheo** [comment]
已修复，可以直接下载仓库的b3版本体验，也可以等待未来在应用商店推送

**Comment by carolcoral** [comment]
谢佬

**Comment by carolcoral** [comment]
佬，这个好像并没有修复，是要重启容器么
https://oyiso.xindu.site/?preview-theme=theme-heolink

**Comment by zhheo** [comment]
不需要重启
