### ISSUE TITLE
【优化】底部位置能否进行优化

### ISSUE THREAD

**Issue by carolcoral** [zhheo/halo-theme-heolink#7]
目前的底部是完全紧贴的，能否增加padding以美化或兼容手动控制页脚，例如支持一个页脚区域填写html或者markdown内容用来填充页脚

<img width="1680" alt="image" src="https://github.com/zhheo/halo-theme-heolink/assets/8952687/5d1b962c-9566-4324-8e1f-c7d9f2f37b8c">

**Comment by zhheo** [comment]
已修复，可以直接下载仓库的beta版本体验，也可以等待未来在应用商店推送

**Comment by carolcoral** [comment]
谢佬

**Comment by carolcoral** [comment]
佬，最新版本是三天前的0.6.1，是不是不对呢

**Comment by zhheo** [comment]
新版本发布前我需要测试，所以我之前说的意思是你可以直接下仓库，或者等测试完了之后我发布的时候再更
现在已更新
