### ISSUE TITLE
提一个小小的功能供大佬参考：常用链接

### ISSUE THREAD

**Issue by penguin806** [zhheo/halo-theme-heolink#8]
可以前端js监听每个链接的click事件，保存链接的打开次数（或访问时间）到localStorage或者cookie中，然后增加一个分类，读取访问次数TOP5，或者最近访问的5个链接，放入常用链接里。

另外，可以提供前端自定义的功能，监听contextmenu事件重写右键菜单，比如用户不需要某个链接，可以右键选择隐藏，选择隐藏的项目也保存在前端localStorage，这样子可以节省不同用户日常使用时找链接位置的时间。

**Comment by zhheo** [comment]
heolink的初衷只是为了博主单向输出的导航工具站，每个用户千人千面的自定义到航站完全可以使用浏览器插件等方式更加优雅的解决，所以目前没有向这方面扩展的计划。heolink并不是浏览器导航的代替，也不是浏览器插件的代替，也无法成为普通用户的主页，他更像是一个聚合站，让用户去发现更多站点的一个项目。
所以目前无这些方向的改进计划。
