### ISSUE TITLE
【美化】美化标题顶部间距

### ISSUE THREAD

**Issue by carolcoral** [zhheo/halo-theme-heolink#9]
洪哥，点击左侧跳转到对应栏目的时候，标题顶部距离是0，不是很美观，能不能加点pandding呢

<img width="1675" alt="image" src="https://github.com/zhheo/halo-theme-heolink/assets/8952687/56d2c23e-e7e8-46c2-b6c2-be49aed98182">

**Comment by zhheo** [comment]
已优化，下个版本更新
